Allow channel::package in package specifications
conda-incubator/conda-lock pull request #207
Opened 2022-07-09 01:19 UTC by mariusvniekerk

This closes #188 

This should allow us to be able to safely specify the channel as part of a lock spec.

Since this is a strict superset of the lockfile format we're choosing to not to increment the version number of a the lockfile spec here.

2022-07-09 19:06 UTC, ericdill requested changes
~Add some docs to the new code~ 

edit1: tried to use the web editor to add some docs. looks like that failed. lemme try again

edit2: ok successfully pushed to your branch using the web editor 🎉

2022-07-09 19:06 UTC, ericdill commented on tests/test-channel-inversion/environment.yaml
> +  - nvidia
anything special about rapidsai and nvidia here? or could these be any channels. might be kind to future maintenance to leave a note about why you picked these two channels

2022-07-09 19:10 UTC, ericdill approved these changes
web editor was confusing. i was trying to leave _my_ changes as a thing for _you_ to approve. this PR looks fine as is, i just had some minor things to point out

2022-07-10 19:26 UTC, mariusvniekerk commented on conda_lock/src_parser/conda_common.py
> +        channel_str = None
I trust the behavior of matchspec about as far as i can throw it, so keeping it expliict here

2022-07-11 12:37 UTC, merged