Do not use `--kind=explicit`
conda-incubator/conda-lock pull request #288
Opened 2022-11-24 07:20 UTC by sebastian-luna-valero

Fixes https://github.com/conda-incubator/conda-lock/issues/285

2022-11-24 15:26 UTC, maresb requested changes

2022-11-24 15:26 UTC, maresb commented on docs/pip.md
> +with `conda-lock --file=environment.yml`)
To address https://github.com/conda-incubator/conda-lock/issues/285#issuecomment-1326553508, 

```suggestion
We recommend avoiding the `--kind=explicit` flag when there are `pip`
dependencies. Most tools (except for `conda-lock install`) do not recognize
`pip` dependencies from explicit lockfiles, so they may be silently ignored.
The default lockfile format explicitly supports pip dependencies.
```

2022-11-24 18:33 UTC, maresb approved these changes

2022-11-24 19:13 UTC, maresb commented
We could also omit a warning from `conda-lock` itself. How about
```python
        if len(pip_deps) > 0:
            logger.warning(
                "WARNING: installation of pip dependencies is only supported "
                "by the 'conda-lock install' command. Other tools may silently "
                "ignore them. For portability, we recommend using the newer "
                "unified lockfile format (i.e. removing the --kind=explicit "
                "argument."
            )
```

right [here](https://github.com/conda-incubator/conda-lock/blob/e1feddd058940dca4227e00927ff61e84901a2eb/conda_lock/conda_lock.py#L677)?

2022-11-25 06:38 UTC, sebastian-luna-valero commented
Good idea, done!

2022-11-26 19:01 UTC, merged